# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_designe.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 500)
        Form.setMinimumSize(QtCore.QSize(800, 500))
        Form.setMaximumSize(QtCore.QSize(800, 500))
        self.monitor = QtWidgets.QLabel(Form)
        self.monitor.setGeometry(QtCore.QRect(30, 60, 741, 341))
        self.monitor.setText("")
        self.monitor.setObjectName("monitor")
        self.line_cord = QtWidgets.QLineEdit(Form)
        self.line_cord.setGeometry(QtCore.QRect(30, 430, 171, 20))
        self.line_cord.setObjectName("line_cord")
        self.btn_search = QtWidgets.QPushButton(Form)
        self.btn_search.setGeometry(QtCore.QRect(700, 430, 75, 23))
        self.btn_search.setObjectName("btn_search")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(230, 430, 91, 22))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.sp_size = QtWidgets.QSpinBox(self.widget)
        self.sp_size.setMinimum(1)
        self.sp_size.setMaximum(100)
        self.sp_size.setObjectName("sp_size")
        self.horizontalLayout.addWidget(self.sp_size)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Карты"))
        self.line_cord.setText(_translate("Form", "Введите координаты"))
        self.btn_search.setText(_translate("Form", "Найти"))
        self.label.setText(_translate("Form", "Маштаб:"))
