# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_designe.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 500)
        Form.setMinimumSize(QtCore.QSize(600, 500))
        Form.setMaximumSize(QtCore.QSize(600, 500))
        self.monitor = QtWidgets.QLabel(Form)
        self.monitor.setGeometry(QtCore.QRect(30, 60, 531, 341))
        self.monitor.setText("")
        self.monitor.setObjectName("monitor")
        self.line_cord = QtWidgets.QLineEdit(Form)
        self.line_cord.setGeometry(QtCore.QRect(30, 430, 171, 20))
        self.line_cord.setObjectName("line_cord")
        self.btn_search = QtWidgets.QPushButton(Form)
        self.btn_search.setGeometry(QtCore.QRect(500, 450, 75, 23))
        self.btn_search.setObjectName("btn_search")
        self.sp_size = QtWidgets.QSpinBox(Form)
        self.sp_size.setGeometry(QtCore.QRect(100, 460, 42, 22))
        self.sp_size.setMinimum(1)
        self.sp_size.setMaximum(100)
        self.sp_size.setObjectName("sp_size")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 460, 51, 16))
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Карты"))
        self.line_cord.setText(_translate("Form", "Введите координаты"))
        self.btn_search.setText(_translate("Form", "Найти"))
        self.label.setText(_translate("Form", "Маштаб:"))
